# Generated by Django 4.2.5 on 2024-09-07 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0006_savedrecipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedRecipe',
        ),
    ]
